[project]
name = "flappy-bird"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.17.2",
    "arcade>=3.3.3",
    "pydantic-settings>=2.12.0",
    "sqlalchemy>=2.0.45",
]
